# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class BtDetail(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'trilaterated_latitude': 'float',
        'trilaterated_longitude': 'float',
        'best_cluster_wi_gle_qo_s': 'int',
        'first_seen': 'datetime',
        'last_seen': 'datetime',
        'last_update': 'datetime',
        'street_address': 'StreetAddress',
        'network_id': 'str',
        'name': 'str',
        'type': 'str',
        'capabilities': 'list[str]',
        'device_type': 'int',
        'location_clusters': 'list[BtLocationCluster]'
    }

    attribute_map = {
        'trilaterated_latitude': 'trilateratedLatitude',
        'trilaterated_longitude': 'trilateratedLongitude',
        'best_cluster_wi_gle_qo_s': 'bestClusterWiGLEQoS',
        'first_seen': 'firstSeen',
        'last_seen': 'lastSeen',
        'last_update': 'lastUpdate',
        'street_address': 'streetAddress',
        'network_id': 'networkId',
        'name': 'name',
        'type': 'type',
        'capabilities': 'capabilities',
        'device_type': 'deviceType',
        'location_clusters': 'locationClusters'
    }

    def __init__(self, trilaterated_latitude=None, trilaterated_longitude=None, best_cluster_wi_gle_qo_s=None, first_seen=None, last_seen=None, last_update=None, street_address=None, network_id=None, name=None, type=None, capabilities=None, device_type=None, location_clusters=None, _configuration=None):  # noqa: E501
        """BtDetail - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._trilaterated_latitude = None
        self._trilaterated_longitude = None
        self._best_cluster_wi_gle_qo_s = None
        self._first_seen = None
        self._last_seen = None
        self._last_update = None
        self._street_address = None
        self._network_id = None
        self._name = None
        self._type = None
        self._capabilities = None
        self._device_type = None
        self._location_clusters = None
        self.discriminator = None

        if trilaterated_latitude is not None:
            self.trilaterated_latitude = trilaterated_latitude
        if trilaterated_longitude is not None:
            self.trilaterated_longitude = trilaterated_longitude
        if best_cluster_wi_gle_qo_s is not None:
            self.best_cluster_wi_gle_qo_s = best_cluster_wi_gle_qo_s
        if first_seen is not None:
            self.first_seen = first_seen
        if last_seen is not None:
            self.last_seen = last_seen
        if last_update is not None:
            self.last_update = last_update
        if street_address is not None:
            self.street_address = street_address
        self.network_id = network_id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if capabilities is not None:
            self.capabilities = capabilities
        if device_type is not None:
            self.device_type = device_type
        if location_clusters is not None:
            self.location_clusters = location_clusters

    @property
    def trilaterated_latitude(self):
        """Gets the trilaterated_latitude of this BtDetail.  # noqa: E501


        :return: The trilaterated_latitude of this BtDetail.  # noqa: E501
        :rtype: float
        """
        return self._trilaterated_latitude

    @trilaterated_latitude.setter
    def trilaterated_latitude(self, trilaterated_latitude):
        """Sets the trilaterated_latitude of this BtDetail.


        :param trilaterated_latitude: The trilaterated_latitude of this BtDetail.  # noqa: E501
        :type: float
        """

        self._trilaterated_latitude = trilaterated_latitude

    @property
    def trilaterated_longitude(self):
        """Gets the trilaterated_longitude of this BtDetail.  # noqa: E501


        :return: The trilaterated_longitude of this BtDetail.  # noqa: E501
        :rtype: float
        """
        return self._trilaterated_longitude

    @trilaterated_longitude.setter
    def trilaterated_longitude(self, trilaterated_longitude):
        """Sets the trilaterated_longitude of this BtDetail.


        :param trilaterated_longitude: The trilaterated_longitude of this BtDetail.  # noqa: E501
        :type: float
        """

        self._trilaterated_longitude = trilaterated_longitude

    @property
    def best_cluster_wi_gle_qo_s(self):
        """Gets the best_cluster_wi_gle_qo_s of this BtDetail.  # noqa: E501


        :return: The best_cluster_wi_gle_qo_s of this BtDetail.  # noqa: E501
        :rtype: int
        """
        return self._best_cluster_wi_gle_qo_s

    @best_cluster_wi_gle_qo_s.setter
    def best_cluster_wi_gle_qo_s(self, best_cluster_wi_gle_qo_s):
        """Sets the best_cluster_wi_gle_qo_s of this BtDetail.


        :param best_cluster_wi_gle_qo_s: The best_cluster_wi_gle_qo_s of this BtDetail.  # noqa: E501
        :type: int
        """

        self._best_cluster_wi_gle_qo_s = best_cluster_wi_gle_qo_s

    @property
    def first_seen(self):
        """Gets the first_seen of this BtDetail.  # noqa: E501


        :return: The first_seen of this BtDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._first_seen

    @first_seen.setter
    def first_seen(self, first_seen):
        """Sets the first_seen of this BtDetail.


        :param first_seen: The first_seen of this BtDetail.  # noqa: E501
        :type: datetime
        """

        self._first_seen = first_seen

    @property
    def last_seen(self):
        """Gets the last_seen of this BtDetail.  # noqa: E501


        :return: The last_seen of this BtDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._last_seen

    @last_seen.setter
    def last_seen(self, last_seen):
        """Sets the last_seen of this BtDetail.


        :param last_seen: The last_seen of this BtDetail.  # noqa: E501
        :type: datetime
        """

        self._last_seen = last_seen

    @property
    def last_update(self):
        """Gets the last_update of this BtDetail.  # noqa: E501


        :return: The last_update of this BtDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._last_update

    @last_update.setter
    def last_update(self, last_update):
        """Sets the last_update of this BtDetail.


        :param last_update: The last_update of this BtDetail.  # noqa: E501
        :type: datetime
        """

        self._last_update = last_update

    @property
    def street_address(self):
        """Gets the street_address of this BtDetail.  # noqa: E501


        :return: The street_address of this BtDetail.  # noqa: E501
        :rtype: StreetAddress
        """
        return self._street_address

    @street_address.setter
    def street_address(self, street_address):
        """Sets the street_address of this BtDetail.


        :param street_address: The street_address of this BtDetail.  # noqa: E501
        :type: StreetAddress
        """

        self._street_address = street_address

    @property
    def network_id(self):
        """Gets the network_id of this BtDetail.  # noqa: E501


        :return: The network_id of this BtDetail.  # noqa: E501
        :rtype: str
        """
        return self._network_id

    @network_id.setter
    def network_id(self, network_id):
        """Sets the network_id of this BtDetail.


        :param network_id: The network_id of this BtDetail.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and network_id is None:
            raise ValueError("Invalid value for `network_id`, must not be `None`")  # noqa: E501

        self._network_id = network_id

    @property
    def name(self):
        """Gets the name of this BtDetail.  # noqa: E501


        :return: The name of this BtDetail.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this BtDetail.


        :param name: The name of this BtDetail.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this BtDetail.  # noqa: E501


        :return: The type of this BtDetail.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this BtDetail.


        :param type: The type of this BtDetail.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def capabilities(self):
        """Gets the capabilities of this BtDetail.  # noqa: E501


        :return: The capabilities of this BtDetail.  # noqa: E501
        :rtype: list[str]
        """
        return self._capabilities

    @capabilities.setter
    def capabilities(self, capabilities):
        """Sets the capabilities of this BtDetail.


        :param capabilities: The capabilities of this BtDetail.  # noqa: E501
        :type: list[str]
        """

        self._capabilities = capabilities

    @property
    def device_type(self):
        """Gets the device_type of this BtDetail.  # noqa: E501


        :return: The device_type of this BtDetail.  # noqa: E501
        :rtype: int
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this BtDetail.


        :param device_type: The device_type of this BtDetail.  # noqa: E501
        :type: int
        """

        self._device_type = device_type

    @property
    def location_clusters(self):
        """Gets the location_clusters of this BtDetail.  # noqa: E501


        :return: The location_clusters of this BtDetail.  # noqa: E501
        :rtype: list[BtLocationCluster]
        """
        return self._location_clusters

    @location_clusters.setter
    def location_clusters(self, location_clusters):
        """Sets the location_clusters of this BtDetail.


        :param location_clusters: The location_clusters of this BtDetail.  # noqa: E501
        :type: list[BtLocationCluster]
        """

        self._location_clusters = location_clusters

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BtDetail, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BtDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, BtDetail):
            return True

        return self.to_dict() != other.to_dict()
