# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class CellSiteChannel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'channel': 'int',
        'latitude': 'float',
        'longitude': 'float',
        'qos': 'int'
    }

    attribute_map = {
        'channel': 'channel',
        'latitude': 'latitude',
        'longitude': 'longitude',
        'qos': 'qos'
    }

    def __init__(self, channel=None, latitude=None, longitude=None, qos=None, _configuration=None):  # noqa: E501
        """CellSiteChannel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._channel = None
        self._latitude = None
        self._longitude = None
        self._qos = None
        self.discriminator = None

        if channel is not None:
            self.channel = channel
        if latitude is not None:
            self.latitude = latitude
        if longitude is not None:
            self.longitude = longitude
        if qos is not None:
            self.qos = qos

    @property
    def channel(self):
        """Gets the channel of this CellSiteChannel.  # noqa: E501


        :return: The channel of this CellSiteChannel.  # noqa: E501
        :rtype: int
        """
        return self._channel

    @channel.setter
    def channel(self, channel):
        """Sets the channel of this CellSiteChannel.


        :param channel: The channel of this CellSiteChannel.  # noqa: E501
        :type: int
        """

        self._channel = channel

    @property
    def latitude(self):
        """Gets the latitude of this CellSiteChannel.  # noqa: E501


        :return: The latitude of this CellSiteChannel.  # noqa: E501
        :rtype: float
        """
        return self._latitude

    @latitude.setter
    def latitude(self, latitude):
        """Sets the latitude of this CellSiteChannel.


        :param latitude: The latitude of this CellSiteChannel.  # noqa: E501
        :type: float
        """

        self._latitude = latitude

    @property
    def longitude(self):
        """Gets the longitude of this CellSiteChannel.  # noqa: E501


        :return: The longitude of this CellSiteChannel.  # noqa: E501
        :rtype: float
        """
        return self._longitude

    @longitude.setter
    def longitude(self, longitude):
        """Sets the longitude of this CellSiteChannel.


        :param longitude: The longitude of this CellSiteChannel.  # noqa: E501
        :type: float
        """

        self._longitude = longitude

    @property
    def qos(self):
        """Gets the qos of this CellSiteChannel.  # noqa: E501


        :return: The qos of this CellSiteChannel.  # noqa: E501
        :rtype: int
        """
        return self._qos

    @qos.setter
    def qos(self, qos):
        """Sets the qos of this CellSiteChannel.


        :param qos: The qos of this CellSiteChannel.  # noqa: E501
        :type: int
        """

        self._qos = qos

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CellSiteChannel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CellSiteChannel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, CellSiteChannel):
            return True

        return self.to_dict() != other.to_dict()
