# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ChannelDetailResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'results_exceed_limit': 'bool',
        'results': 'list[CellSiteChannel]',
        'result_type': 'str'
    }

    attribute_map = {
        'success': 'success',
        'results_exceed_limit': 'resultsExceedLimit',
        'results': 'results',
        'result_type': 'resultType'
    }

    def __init__(self, success=None, results_exceed_limit=None, results=None, result_type=None, _configuration=None):  # noqa: E501
        """ChannelDetailResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._success = None
        self._results_exceed_limit = None
        self._results = None
        self._result_type = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if results_exceed_limit is not None:
            self.results_exceed_limit = results_exceed_limit
        if results is not None:
            self.results = results
        if result_type is not None:
            self.result_type = result_type

    @property
    def success(self):
        """Gets the success of this ChannelDetailResponse.  # noqa: E501


        :return: The success of this ChannelDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this ChannelDetailResponse.


        :param success: The success of this ChannelDetailResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def results_exceed_limit(self):
        """Gets the results_exceed_limit of this ChannelDetailResponse.  # noqa: E501


        :return: The results_exceed_limit of this ChannelDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._results_exceed_limit

    @results_exceed_limit.setter
    def results_exceed_limit(self, results_exceed_limit):
        """Sets the results_exceed_limit of this ChannelDetailResponse.


        :param results_exceed_limit: The results_exceed_limit of this ChannelDetailResponse.  # noqa: E501
        :type: bool
        """

        self._results_exceed_limit = results_exceed_limit

    @property
    def results(self):
        """Gets the results of this ChannelDetailResponse.  # noqa: E501


        :return: The results of this ChannelDetailResponse.  # noqa: E501
        :rtype: list[CellSiteChannel]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this ChannelDetailResponse.


        :param results: The results of this ChannelDetailResponse.  # noqa: E501
        :type: list[CellSiteChannel]
        """

        self._results = results

    @property
    def result_type(self):
        """Gets the result_type of this ChannelDetailResponse.  # noqa: E501


        :return: The result_type of this ChannelDetailResponse.  # noqa: E501
        :rtype: str
        """
        return self._result_type

    @result_type.setter
    def result_type(self, result_type):
        """Sets the result_type of this ChannelDetailResponse.


        :param result_type: The result_type of this ChannelDetailResponse.  # noqa: E501
        :type: str
        """

        self._result_type = result_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ChannelDetailResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ChannelDetailResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ChannelDetailResponse):
            return True

        return self.to_dict() != other.to_dict()
