# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EncryptionStat(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'wep': 'str',
        'count': 'int'
    }

    attribute_map = {
        'wep': 'wep',
        'count': 'count'
    }

    def __init__(self, wep=None, count=None, _configuration=None):  # noqa: E501
        """EncryptionStat - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._wep = None
        self._count = None
        self.discriminator = None

        if wep is not None:
            self.wep = wep
        if count is not None:
            self.count = count

    @property
    def wep(self):
        """Gets the wep of this EncryptionStat.  # noqa: E501


        :return: The wep of this EncryptionStat.  # noqa: E501
        :rtype: str
        """
        return self._wep

    @wep.setter
    def wep(self, wep):
        """Sets the wep of this EncryptionStat.


        :param wep: The wep of this EncryptionStat.  # noqa: E501
        :type: str
        """

        self._wep = wep

    @property
    def count(self):
        """Gets the count of this EncryptionStat.  # noqa: E501


        :return: The count of this EncryptionStat.  # noqa: E501
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this EncryptionStat.


        :param count: The count of this EncryptionStat.  # noqa: E501
        :type: int
        """

        self._count = count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EncryptionStat, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EncryptionStat):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EncryptionStat):
            return True

        return self.to_dict() != other.to_dict()
