# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class NetCommentResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'comment': 'str',
        'netid': 'str'
    }

    attribute_map = {
        'success': 'success',
        'comment': 'comment',
        'netid': 'netid'
    }

    def __init__(self, success=None, comment=None, netid=None, _configuration=None):  # noqa: E501
        """NetCommentResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._success = None
        self._comment = None
        self._netid = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if comment is not None:
            self.comment = comment
        if netid is not None:
            self.netid = netid

    @property
    def success(self):
        """Gets the success of this NetCommentResponse.  # noqa: E501


        :return: The success of this NetCommentResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this NetCommentResponse.


        :param success: The success of this NetCommentResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def comment(self):
        """Gets the comment of this NetCommentResponse.  # noqa: E501


        :return: The comment of this NetCommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._comment

    @comment.setter
    def comment(self, comment):
        """Sets the comment of this NetCommentResponse.


        :param comment: The comment of this NetCommentResponse.  # noqa: E501
        :type: str
        """

        self._comment = comment

    @property
    def netid(self):
        """Gets the netid of this NetCommentResponse.  # noqa: E501


        :return: The netid of this NetCommentResponse.  # noqa: E501
        :rtype: str
        """
        return self._netid

    @netid.setter
    def netid(self, netid):
        """Sets the netid of this NetCommentResponse.


        :param netid: The netid of this NetCommentResponse.  # noqa: E501
        :type: str
        """

        self._netid = netid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NetCommentResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NetCommentResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, NetCommentResponse):
            return True

        return self.to_dict() != other.to_dict()
