# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class RegionResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'regions': 'list[RegionStat]',
        'postal_code': 'list[PostalStat]',
        'encryption': 'list[EncryptionStat]'
    }

    attribute_map = {
        'success': 'success',
        'regions': 'regions',
        'postal_code': 'postalCode',
        'encryption': 'encryption'
    }

    def __init__(self, success=None, regions=None, postal_code=None, encryption=None, _configuration=None):  # noqa: E501
        """RegionResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._success = None
        self._regions = None
        self._postal_code = None
        self._encryption = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if regions is not None:
            self.regions = regions
        if postal_code is not None:
            self.postal_code = postal_code
        if encryption is not None:
            self.encryption = encryption

    @property
    def success(self):
        """Gets the success of this RegionResponse.  # noqa: E501


        :return: The success of this RegionResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this RegionResponse.


        :param success: The success of this RegionResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def regions(self):
        """Gets the regions of this RegionResponse.  # noqa: E501


        :return: The regions of this RegionResponse.  # noqa: E501
        :rtype: list[RegionStat]
        """
        return self._regions

    @regions.setter
    def regions(self, regions):
        """Sets the regions of this RegionResponse.


        :param regions: The regions of this RegionResponse.  # noqa: E501
        :type: list[RegionStat]
        """

        self._regions = regions

    @property
    def postal_code(self):
        """Gets the postal_code of this RegionResponse.  # noqa: E501


        :return: The postal_code of this RegionResponse.  # noqa: E501
        :rtype: list[PostalStat]
        """
        return self._postal_code

    @postal_code.setter
    def postal_code(self, postal_code):
        """Sets the postal_code of this RegionResponse.


        :param postal_code: The postal_code of this RegionResponse.  # noqa: E501
        :type: list[PostalStat]
        """

        self._postal_code = postal_code

    @property
    def encryption(self):
        """Gets the encryption of this RegionResponse.  # noqa: E501


        :return: The encryption of this RegionResponse.  # noqa: E501
        :rtype: list[EncryptionStat]
        """
        return self._encryption

    @encryption.setter
    def encryption(self, encryption):
        """Sets the encryption of this RegionResponse.


        :param encryption: The encryption of this RegionResponse.  # noqa: E501
        :type: list[EncryptionStat]
        """

        self._encryption = encryption

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RegionResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegionResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, RegionResponse):
            return True

        return self.to_dict() != other.to_dict()
