# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TransidResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file': 'str',
        'size': 'int',
        'trans_id': 'str'
    }

    attribute_map = {
        'file': 'file',
        'size': 'size',
        'trans_id': 'transId'
    }

    def __init__(self, file=None, size=None, trans_id=None, _configuration=None):  # noqa: E501
        """TransidResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._file = None
        self._size = None
        self._trans_id = None
        self.discriminator = None

        if file is not None:
            self.file = file
        if size is not None:
            self.size = size
        if trans_id is not None:
            self.trans_id = trans_id

    @property
    def file(self):
        """Gets the file of this TransidResponse.  # noqa: E501


        :return: The file of this TransidResponse.  # noqa: E501
        :rtype: str
        """
        return self._file

    @file.setter
    def file(self, file):
        """Sets the file of this TransidResponse.


        :param file: The file of this TransidResponse.  # noqa: E501
        :type: str
        """

        self._file = file

    @property
    def size(self):
        """Gets the size of this TransidResponse.  # noqa: E501


        :return: The size of this TransidResponse.  # noqa: E501
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size):
        """Sets the size of this TransidResponse.


        :param size: The size of this TransidResponse.  # noqa: E501
        :type: int
        """

        self._size = size

    @property
    def trans_id(self):
        """Gets the trans_id of this TransidResponse.  # noqa: E501


        :return: The trans_id of this TransidResponse.  # noqa: E501
        :rtype: str
        """
        return self._trans_id

    @trans_id.setter
    def trans_id(self, trans_id):
        """Sets the trans_id of this TransidResponse.


        :param trans_id: The trans_id of this TransidResponse.  # noqa: E501
        :type: str
        """

        self._trans_id = trans_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TransidResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransidResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TransidResponse):
            return True

        return self.to_dict() != other.to_dict()
