# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class TranslogResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'results': 'list[TransLog]',
        'processing_queue_depth': 'int',
        'geo_queue_depth': 'int',
        'trilateration_queue_depth': 'int'
    }

    attribute_map = {
        'success': 'success',
        'results': 'results',
        'processing_queue_depth': 'processingQueueDepth',
        'geo_queue_depth': 'geoQueueDepth',
        'trilateration_queue_depth': 'trilaterationQueueDepth'
    }

    def __init__(self, success=None, results=None, processing_queue_depth=None, geo_queue_depth=None, trilateration_queue_depth=None, _configuration=None):  # noqa: E501
        """TranslogResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._success = None
        self._results = None
        self._processing_queue_depth = None
        self._geo_queue_depth = None
        self._trilateration_queue_depth = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if results is not None:
            self.results = results
        if processing_queue_depth is not None:
            self.processing_queue_depth = processing_queue_depth
        if geo_queue_depth is not None:
            self.geo_queue_depth = geo_queue_depth
        if trilateration_queue_depth is not None:
            self.trilateration_queue_depth = trilateration_queue_depth

    @property
    def success(self):
        """Gets the success of this TranslogResponse.  # noqa: E501


        :return: The success of this TranslogResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this TranslogResponse.


        :param success: The success of this TranslogResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def results(self):
        """Gets the results of this TranslogResponse.  # noqa: E501


        :return: The results of this TranslogResponse.  # noqa: E501
        :rtype: list[TransLog]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this TranslogResponse.


        :param results: The results of this TranslogResponse.  # noqa: E501
        :type: list[TransLog]
        """

        self._results = results

    @property
    def processing_queue_depth(self):
        """Gets the processing_queue_depth of this TranslogResponse.  # noqa: E501


        :return: The processing_queue_depth of this TranslogResponse.  # noqa: E501
        :rtype: int
        """
        return self._processing_queue_depth

    @processing_queue_depth.setter
    def processing_queue_depth(self, processing_queue_depth):
        """Sets the processing_queue_depth of this TranslogResponse.


        :param processing_queue_depth: The processing_queue_depth of this TranslogResponse.  # noqa: E501
        :type: int
        """

        self._processing_queue_depth = processing_queue_depth

    @property
    def geo_queue_depth(self):
        """Gets the geo_queue_depth of this TranslogResponse.  # noqa: E501


        :return: The geo_queue_depth of this TranslogResponse.  # noqa: E501
        :rtype: int
        """
        return self._geo_queue_depth

    @geo_queue_depth.setter
    def geo_queue_depth(self, geo_queue_depth):
        """Sets the geo_queue_depth of this TranslogResponse.


        :param geo_queue_depth: The geo_queue_depth of this TranslogResponse.  # noqa: E501
        :type: int
        """

        self._geo_queue_depth = geo_queue_depth

    @property
    def trilateration_queue_depth(self):
        """Gets the trilateration_queue_depth of this TranslogResponse.  # noqa: E501


        :return: The trilateration_queue_depth of this TranslogResponse.  # noqa: E501
        :rtype: int
        """
        return self._trilateration_queue_depth

    @trilateration_queue_depth.setter
    def trilateration_queue_depth(self, trilateration_queue_depth):
        """Sets the trilateration_queue_depth of this TranslogResponse.


        :param trilateration_queue_depth: The trilateration_queue_depth of this TranslogResponse.  # noqa: E501
        :type: int
        """

        self._trilateration_queue_depth = trilateration_queue_depth

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranslogResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranslogResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TranslogResponse):
            return True

        return self.to_dict() != other.to_dict()
