# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class UploadResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'warning': 'str',
        'results': 'UploadResultsResponse',
        'observer': 'str'
    }

    attribute_map = {
        'success': 'success',
        'warning': 'warning',
        'results': 'results',
        'observer': 'observer'
    }

    def __init__(self, success=None, warning=None, results=None, observer=None, _configuration=None):  # noqa: E501
        """UploadResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._success = None
        self._warning = None
        self._results = None
        self._observer = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if warning is not None:
            self.warning = warning
        if results is not None:
            self.results = results
        if observer is not None:
            self.observer = observer

    @property
    def success(self):
        """Gets the success of this UploadResponse.  # noqa: E501


        :return: The success of this UploadResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this UploadResponse.


        :param success: The success of this UploadResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def warning(self):
        """Gets the warning of this UploadResponse.  # noqa: E501


        :return: The warning of this UploadResponse.  # noqa: E501
        :rtype: str
        """
        return self._warning

    @warning.setter
    def warning(self, warning):
        """Sets the warning of this UploadResponse.


        :param warning: The warning of this UploadResponse.  # noqa: E501
        :type: str
        """

        self._warning = warning

    @property
    def results(self):
        """Gets the results of this UploadResponse.  # noqa: E501


        :return: The results of this UploadResponse.  # noqa: E501
        :rtype: UploadResultsResponse
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this UploadResponse.


        :param results: The results of this UploadResponse.  # noqa: E501
        :type: UploadResultsResponse
        """

        self._results = results

    @property
    def observer(self):
        """Gets the observer of this UploadResponse.  # noqa: E501


        :return: The observer of this UploadResponse.  # noqa: E501
        :rtype: str
        """
        return self._observer

    @observer.setter
    def observer(self, observer):
        """Sets the observer of this UploadResponse.


        :param observer: The observer of this UploadResponse.  # noqa: E501
        :type: str
        """

        self._observer = observer

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UploadResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UploadResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, UploadResponse):
            return True

        return self.to_dict() != other.to_dict()
