# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class WiFiNetworkDetailResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'success': 'bool',
        'cdma': 'bool',
        'gsm': 'bool',
        'lte': 'bool',
        'wcdma': 'bool',
        'wifi': 'bool',
        'addresses': 'list[GeocodingResponse]',
        'results': 'list[WiFiNetworkWithLocation]'
    }

    attribute_map = {
        'success': 'success',
        'cdma': 'cdma',
        'gsm': 'gsm',
        'lte': 'lte',
        'wcdma': 'wcdma',
        'wifi': 'wifi',
        'addresses': 'addresses',
        'results': 'results'
    }

    def __init__(self, success=None, cdma=None, gsm=None, lte=None, wcdma=None, wifi=None, addresses=None, results=None, _configuration=None):  # noqa: E501
        """WiFiNetworkDetailResponse - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._success = None
        self._cdma = None
        self._gsm = None
        self._lte = None
        self._wcdma = None
        self._wifi = None
        self._addresses = None
        self._results = None
        self.discriminator = None

        if success is not None:
            self.success = success
        if cdma is not None:
            self.cdma = cdma
        if gsm is not None:
            self.gsm = gsm
        if lte is not None:
            self.lte = lte
        if wcdma is not None:
            self.wcdma = wcdma
        if wifi is not None:
            self.wifi = wifi
        if addresses is not None:
            self.addresses = addresses
        if results is not None:
            self.results = results

    @property
    def success(self):
        """Gets the success of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The success of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._success

    @success.setter
    def success(self, success):
        """Sets the success of this WiFiNetworkDetailResponse.


        :param success: The success of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: bool
        """

        self._success = success

    @property
    def cdma(self):
        """Gets the cdma of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The cdma of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._cdma

    @cdma.setter
    def cdma(self, cdma):
        """Sets the cdma of this WiFiNetworkDetailResponse.


        :param cdma: The cdma of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: bool
        """

        self._cdma = cdma

    @property
    def gsm(self):
        """Gets the gsm of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The gsm of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._gsm

    @gsm.setter
    def gsm(self, gsm):
        """Sets the gsm of this WiFiNetworkDetailResponse.


        :param gsm: The gsm of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: bool
        """

        self._gsm = gsm

    @property
    def lte(self):
        """Gets the lte of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The lte of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._lte

    @lte.setter
    def lte(self, lte):
        """Sets the lte of this WiFiNetworkDetailResponse.


        :param lte: The lte of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: bool
        """

        self._lte = lte

    @property
    def wcdma(self):
        """Gets the wcdma of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The wcdma of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._wcdma

    @wcdma.setter
    def wcdma(self, wcdma):
        """Sets the wcdma of this WiFiNetworkDetailResponse.


        :param wcdma: The wcdma of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: bool
        """

        self._wcdma = wcdma

    @property
    def wifi(self):
        """Gets the wifi of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The wifi of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: bool
        """
        return self._wifi

    @wifi.setter
    def wifi(self, wifi):
        """Sets the wifi of this WiFiNetworkDetailResponse.


        :param wifi: The wifi of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: bool
        """

        self._wifi = wifi

    @property
    def addresses(self):
        """Gets the addresses of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The addresses of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: list[GeocodingResponse]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses):
        """Sets the addresses of this WiFiNetworkDetailResponse.


        :param addresses: The addresses of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: list[GeocodingResponse]
        """

        self._addresses = addresses

    @property
    def results(self):
        """Gets the results of this WiFiNetworkDetailResponse.  # noqa: E501


        :return: The results of this WiFiNetworkDetailResponse.  # noqa: E501
        :rtype: list[WiFiNetworkWithLocation]
        """
        return self._results

    @results.setter
    def results(self, results):
        """Sets the results of this WiFiNetworkDetailResponse.


        :param results: The results of this WiFiNetworkDetailResponse.  # noqa: E501
        :type: list[WiFiNetworkWithLocation]
        """

        self._results = results

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WiFiNetworkDetailResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WiFiNetworkDetailResponse):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, WiFiNetworkDetailResponse):
            return True

        return self.to_dict() != other.to_dict()
