# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bluetooth_search_and_information_tools_api import BluetoothSearchAndInformationToolsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBluetoothSearchAndInformationToolsApi(unittest.TestCase):
    """BluetoothSearchAndInformationToolsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.bluetooth_search_and_information_tools_api.BluetoothSearchAndInformationToolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_detail(self):
        """Test case for detail

        Get details and observation records for a single network.  # noqa: E501
        """
        pass

    def test_search(self):
        """Test case for search

        Search the WiGLE Bluetooth database.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
