# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.statistics_and_information_api import StatisticsAndInformationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStatisticsAndInformationApi(unittest.TestCase):
    """StatisticsAndInformationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.statistics_and_information_api.StatisticsAndInformationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_countries(self):
        """Test case for countries

        Get statistics organized by country  # noqa: E501
        """
        pass

    def test_country_region(self):
        """Test case for country_region

        Get statistics for a specified country, organized by region, postal code, and encryption  # noqa: E501
        """
        pass

    def test_general_stats(self):
        """Test case for general_stats

        Get a named map of general statistics  # noqa: E501
        """
        pass

    def test_group_stats(self):
        """Test case for group_stats

        Get group standings  # noqa: E501
        """
        pass

    def test_site_stats(self):
        """Test case for site_stats

        Get a named map of site-level statistics  # noqa: E501
        """
        pass

    def test_stats(self):
        """Test case for stats

        Get user standings  # noqa: E501
        """
        pass

    def test_user_statistics(self):
        """Test case for user_statistics

        Get user statistics  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
