# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.bt_detail import BtDetail  # noqa: E501
from swagger_client.rest import ApiException


class TestBtDetail(unittest.TestCase):
    """BtDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBtDetail(self):
        """Test BtDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.bt_detail.BtDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
