# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.network_search_and_information_tools_api import NetworkSearchAndInformationToolsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNetworkSearchAndInformationToolsApi(unittest.TestCase):
    """NetworkSearchAndInformationToolsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.network_search_and_information_tools_api.NetworkSearchAndInformationToolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_comment(self):
        """Test case for comment

        Add a comment to a network  # noqa: E501
        """
        pass

    def test_detail1(self):
        """Test case for detail1

        Get details and observation records for a single wifi or cell network  # noqa: E501
        """
        pass

    def test_geocode(self):
        """Test case for geocode

        Get coordinates for an address for use in searching  # noqa: E501
        """
        pass

    def test_search2(self):
        """Test case for search2

        Search the WiGLE Wifi database.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
