# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.cell_search_and_information_tools_api import CellSearchAndInformationToolsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCellSearchAndInformationToolsApi(unittest.TestCase):
    """CellSearchAndInformationToolsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.cell_search_and_information_tools_api.CellSearchAndInformationToolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mcc_mnc(self):
        """Test case for mcc_mnc

        Get MCC and MNC codes for Cellular networks  # noqa: E501
        """
        pass

    def test_search1(self):
        """Test case for search1

        Search the WiGLE Cell database.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
