# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.v3_alpha_api import V3ALPHAApi  # noqa: E501
from swagger_client.rest import ApiException


class TestV3ALPHAApi(unittest.TestCase):
    """V3ALPHAApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.v3_alpha_api.V3ALPHAApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bt(self):
        """Test case for bt

        Request detail for a bluetooth network  # noqa: E501
        """
        pass

    def test_cdma_cell(self):
        """Test case for cdma_cell

        Request detail for a CDMA network  # noqa: E501
        """
        pass

    def test_cell(self):
        """Test case for cell

        Request detail for a GSM, LTE, or WCDMA network  # noqa: E501
        """
        pass

    def test_cell_channel(self):
        """Test case for cell_channel

        Request list of channels for GSM, LTE, or WCDMA transmitters in specified region  # noqa: E501
        """
        pass

    def test_wifi(self):
        """Test case for wifi

        Request detail for a WiFi network  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
