# coding: utf-8

"""
    WiGLE API

    Search, upload, and integrate statistics from WiGLE. Use API Name+Token from https://wigle.net/account  # noqa: E501

    OpenAPI spec version: 3.1
    Contact: WiGLE-admin@wigle.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stats_group_management_api import StatsGroupManagementApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStatsGroupManagementApi(unittest.TestCase):
    """StatsGroupManagementApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.stats_group_management_api.StatsGroupManagementApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_admin_group(self):
        """Test case for admin_group

        Get group info as a stats group administrator  # noqa: E501
        """
        pass

    def test_group_members(self):
        """Test case for group_members

        Get group members  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
